### ISSUE TITLE
PHP Fatal error:  Call to undefined function i18n_set_map()

### ISSUE THREAD

**Issue by jaganz** [rodrigofns/zabbix-service-tree#2]
I have blank page and every time this error:

<code>PHP Fatal error:  Call to undefined function i18n_set_map() in /path/to/www/zabbix-service-tree/inc/Install.class.php on line 6</code>

can you help?

**Comment by rodrigofns** [comment]
This function is in "i18n.php" file, can you find it?

**Comment by jaganz** [comment]
yes is in inc/ directory
