### ISSUE TITLE
Melhoria de Compatibilidade com o Mac OS X

### ISSUE THREAD

**Issue by contato318** [rodrigofns/zabbix-service-tree#7]
Olá,
Ao utilizar o zabbix-sevice-tree, verifique que o mesmo não respondia corretamente no momento de acessar o dialogEditService.php.

Verifiquei que o evento nao estava sendo corretamente capturado no index.js, na "treeObj.ctrlClick(function(nodeObj, ev) { NodeCtrlClick(timerObj, treeObj, nodeObj); });".

Realizei a seguinte alteração no  js/TreeGraph.min.js para que o evento da tecla Meta do MAC fosse reconhecida:
--> Onde estava: if(r.ctrlKey)
--> Alterei para: if( r.ctrlKey || r.altKey || r.metaKey)

Favor avaliar a alteração, tavez seja interessante incluir esta alteração no seu código.

**Comment by rodrigofns** [comment]
Não temos interesse em implementações específicas para Macs. De toda forma, obrigado pelo contato.
